version: "3.8"

services:
  oracle: 
    image: ghcr.io/gvenzl/oracle-free:23.7-slim-faststart
    container_name: dreamhome_db
    restart: unless-stopped
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: "admin"
      APP_USER: "admin"
      APP_USER_PASSWORD: "admin"
    volumes:
      - oracle_data:/opt/oracle/oradata
  api:
    build:
      context: ./api 
      dockerfile: Dockerfile 
    container_name: dreamhome_api 
    network_mode: host
    depends_on:
      - oracle 
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/code
    env_file:
      - ./api/.env
    volumes:
      - ./api/code:/code
      - ./api/run.sh:/run.sh 
    command: ["/run.sh"]

  ui:
    build:
      context: ./ui 
      dockerfile: Dockerfile 
    container_name: dreamhome_ui
    # network_mode: host
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - ./ui:/app 
    command: npm run dev

volumes:
  oracle_data:


